# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  push:
    tags:
      - 'v*'

jobs:
  call-build:
    uses: Quansight/rafe/.github/workflows/build-package.yml@master
  
  deploy:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
      
    steps:
    
    - name: Download generated dist
      uses: actions/download-artifact@v3
      with:
        name: rafe-wheel
        path: dist/
        
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
